[package]
name = 'sha3pow'
version = "0.0.1"
edition = '2018'
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
repository = 'https://github.com/substrate-developer-hub/recipes'
description = 'Sha3-based Proof of Work algorithms for Substrate'
license = "GPL-3.0-or-later"

[package.metadata.substrate]
categories = [
	"consensus",
	"recipe",
]
compatibility_version = "2.0.0"

[dependencies]
parity-scale-codec = '2.0.0'
rand = { version = "0.8.0", features = ["small_rng"] }
sha3 = "0.9.1"

# Substrate packages

sc-consensus-pow = '0.9.0'
sp-api = '3.0.0'
sp-consensus-pow = '0.9.0'
sp-core = '3.0.0'
sp-runtime = '3.0.0'
